# Generated by Django 6.0.4 on 2026-05-05 13:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comanda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_creare', models.DateTimeField(auto_now_add=True)),
                ('total', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('status', models.CharField(default='in_asteptare', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Produs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nume', models.CharField(max_length=100)),
                ('descriere', models.TextField()),
                ('pret', models.DecimalField(decimal_places=2, max_digits=6)),
                ('imagine_url', models.URLField(blank=True, default='https://via.placeholder.com/400x300?text=Fara+Imagine', null=True)),
                ('disponibil', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='ElementComanda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantitate', models.PositiveIntegerField(default=1)),
                ('pret_unitar', models.DecimalField(decimal_places=2, max_digits=6)),
                ('comanda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='elemente', to='core.comanda')),
                ('produs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.produs')),
            ],
        ),
    ]
